# Assignment 2: Credit Card Fraud Detection Using ANN

## Objective

Aap ko *Credit Card Fraud Dataset* diya ja raha hai. Is assignment mein aap ne *Artificial Neural Network (ANN)* ka use karte hue transactions ko *fraudulent ya legitimate* classify karna hai.
## Task

Dataset ko preprocess karne ke baad ANN classification model develop karein aur transaction ki fraud/non-fraud prediction karein.

### Target / Output Column

*Output Column:* Class

Generally:

* 0 → Legitimate / Normal Transaction
* 1 → Fraudulent Transaction

Class ko input features mein include nahi karna. Ye aapka *target/output (y)* hoga.

## Requirements

### 1. Data Preprocessing

* Dataset load karein.
* Dataset ka EDA perform karein.
* Missing values check karein.
* Duplicate values check karein.
* Features (X) aur target (y) separate karein.
* Class ki distribution check karein.
* Dataset *imbalanced* hai, is liye imbalance ko properly handle karein.
* Training aur testing data mein split karein.
* Numerical features par *Feature Scaling* apply karein.

### 2. Imbalanced Data Handling

Imbalanced dataset ko handle karne ke liye appropriate technique use karein.

Aap in mein se suitable technique experiment kar sakte hain:

* Class Weights
* Undersampling
* Oversampling
* SMOTE

*Note:* Test data ko artificially balance nahi karna. Test set ko realistic distribution ke sath evaluate karna hai.

### 3. ANN Model

TensorFlow/Keras ka use kar ke ANN classification model develop karein.

Different architectures experiment karein:

* Different hidden layers
* Different neurons
* Different activation functions
* Different optimizers
* Different epochs
* Different batch sizes

### 4. Activation Functions

Kam az kam *3 different activation configurations* try karein, for example:

* ReLU
* Tanh
* Sigmoid

Output layer mein binary classification ke liye appropriate activation function use karein.

### 5. Optimizers

Kam az kam *3 optimizers* experiment karein:

* Adam
* SGD
* RMSprop

Har optimizer ka result compare karein.

### 6. Model Training

Different epochs try karein, for example:

* 20
* 50
* 100

Training ke waqt:

* Training Loss
* Validation Loss
* Performance

observe karein.

### 7. Evaluation

Fraud detection mein sirf *Accuracy* par depend nahi karna.

Neeche diye gaye metrics calculate karein:

* Accuracy
* Precision
* Recall
* F1-Score
* Confusion Matrix

Specially *Recall* ko carefully analyze karein, kyun ke fraud transactions ko correctly detect karna important hai.

### 8. Prediction

Best ANN model select karne ke baad:

* Test dataset par predictions generate karein.
* Kuch sample transactions ki actual aur predicted classes display karein.
* 0 aur 1 predictions ko clearly explain karein.

### 9. Model Comparison

Different experiments ka comparison banayein:

| Model   | Activation | Optimizer | Epochs | Accuracy | Precision | Recall |  F1 |
| ------- | ---------- | --------- | -----: | -------: | --------: | -----: | --: |
| Model 1 | ReLU       | Adam      |     50 |      ... |       ... |    ... | ... |
| Model 2 | Tanh       | SGD       |     50 |      ... |       ... |    ... | ... |
| Model 3 | ReLU       | RMSprop   |    100 |      ... |       ... |    ... | ... |

Aakhir mein identify karein ke *kaunsa model best perform karta hai aur kyun.*

## Important

Sirf ek ANN model train karna sufficient nahi hai. Aap ko *multiple activation functions, optimizers, architectures aur epochs* ke sath experiments karne hain.

*Important:* Fraud dataset imbalanced hai, is liye sirf high accuracy ko successful model na samjhein. Precision, Recall aur F1-Score ko bhi consider karein.

## Submission

Submit the following:

1. Jupyter Notebook / Google Colab file
2. Complete preprocessing code
3. Imbalanced data handling technique
4. ANN model code
5. Different experiments
6. Evaluation metrics
7. Confusion Matrix
8. Final predictions
9. Model comparison
10. Short conclusion

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/creditcard.csv')

In [4]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(1081)

In [7]:
data.drop_duplicates(inplace=True)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 283726 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    283726 non-null  float64
 1   V1      283726 non-null  float64
 2   V2      283726 non-null  float64
 3   V3      283726 non-null  float64
 4   V4      283726 non-null  float64
 5   V5      283726 non-null  float64
 6   V6      283726 non-null  float64
 7   V7      283726 non-null  float64
 8   V8      283726 non-null  float64
 9   V9      283726 non-null  float64
 10  V10     283726 non-null  float64
 11  V11     283726 non-null  float64
 12  V12     283726 non-null  float64
 13  V13     283726 non-null  float64
 14  V14     283726 non-null  float64
 15  V15     283726 non-null  float64
 16  V16     283726 non-null  float64
 17  V17     283726 non-null  float64
 18  V18     283726 non-null  float64
 19  V19     283726 non-null  float64
 20  V20     283726 non-null  float64
 21  V21     283726 non-null  float64
 22  V22     283726 non-null  float64
 23  V23     283726 non-null  float64
 24  V24     283726 non-null  float64
 25  V25     283726 non-null  float64
 26  V26     283726 non-null  float64
 27  V27     283726 non-null  float64
 28  V28     283726 non-null  float64
 29  Amount  283726 non-null  float64
 30  Class   283726 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 69.3 MB

In [9]:
X = data.drop(['Class'],axis=1)
y = data['Class']

In [10]:
y.value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [11]:
data.corr()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
Time,1.000000,0.117927,-0.010556,-0.422054,-0.105845,0.173223,-0.063279,0.085335,-0.038203,-0.007861,...,0.045913,0.143727,0.051474,-0.015954,-0.233262,-0.041818,-0.005171,-0.009305,-0.010559,-0.012359
V1,0.117927,1.000000,0.006875,-0.008112,0.002257,-0.007036,0.000413,-0.009173,-0.001168,0.001828,...,0.002818,-0.001436,-0.001330,-0.000723,-0.000222,-0.000684,-0.015706,-0.004861,-0.230105,-0.094486
V2,-0.010556,0.006875,1.000000,0.005278,-0.001495,0.005210,-0.000594,0.007425,0.002899,-0.000274,...,-0.004897,0.001237,-0.003855,0.000701,-0.001569,0.000253,0.007555,0.001611,-0.533428,0.084624
V3,-0.422054,-0.008112,0.005278,1.000000,0.002829,-0.006879,-0.001511,-0.011721,-0.001815,-0.003579,...,0.003500,-0.000275,0.000449,-0.000072,0.000425,-0.000094,-0.007051,-0.000134,-0.212410,-0.182322
V4,-0.105845,0.002257,-0.001495,0.002829,1.000000,0.001744,-0.000880,0.004657,0.000890,0.002154,...,-0.001034,0.000115,0.000732,-0.000120,0.000162,0.000777,0.001322,0.000231,0.099514,0.129326
V5,0.173223,-0.007036,0.005210,-0.006879,0.001744,1.000000,-0.000938,-0.008709,0.001430,-0.001213,...,0.001622,-0.000559,0.001183,0.000198,0.000069,0.000390,-0.005798,-0.000820,-0.387685,-0.087812
V6,-0.063279,0.000413,-0.000594,-0.001511,-0.000880,-0.000938,1.000000,0.000436,0.003036,-0.000734,...,-0.002134,0.001104,-0.000755,0.001202,0.000697,-0.000028,0.000289,0.000925,0.216389,-0.043915
V7,0.085335,-0.009173,0.007425,-0.011721,0.004657,-0.008709,0.000436,1.000000,-0.006419,-0.004921,...,0.009010,-0.002280,0.003303,-0.000384,-0.000072,0.000624,-0.004537,0.001657,0.400408,-0.172347
V8,-0.038203,-0.001168,0.002899,-0.001815,0.000890,0.001430,0.003036,-0.006419,1.000000,0.001038,...,0.018892,-0.006156,0.004994,0.000113,0.000011,-0.001407,0.000613,-0.000099,-0.104662,0.033068
V9,-0.007861,0.001828,-0.000274,-0.003579,0.002154,-0.001213,-0.000734,-0.004921,0.001038,1.000000,...,0.000679,0.000785,0.000677,-0.000103,-0.000275,0.001253,0.008221,0.005591,-0.044123,-0.094021
V10,0.031068,0.000815,0.000620,-0.009632,0.002753,-0.006050,-0.002180,-0.013617,0.000481,-0.012613,...,0.003777,-0.000481,0.001917,0.000154,-0.000565,0.001089,0.010769,0.009159,-0.102255,-0.206971
V11,-0.248536,0.001028,-0.000633,0.002339,-0.001223,0.000411,-0.000211,0.002454,0.004688,-0.000217,...,-0.002760,-0.000150,-0.000037,0.000080,0.000047,-0.000204,0.001987,0.002562,-0.000015,0.149067
V12,0.125500,-0.001524,0.002266,-0.005900,0.003366,-0.002342,-0.001185,-0.006153,-0.004414,-0.002385,...,0.003285,0.000151,0.000486,0.000588,-0.000181,-0.000138,-0.000929,-0.000613,-0.009254,-0.250711
V13,-0.065958,-0.000568,0.000680,0.000113,0.000177,0.000019,0.000397,-0.000170,-0.001381,0.000745,...,0.000522,0.000016,0.000252,-0.000049,0.000248,-0.000101,-0.001577,-0.000604,0.005209,-0.003897
V14,-0.100316,-0.002663,0.002711,-0.003027,0.002801,-0.001000,0.000184,-0.003816,-0.008387,0.001981,...,0.005633,-0.001906,0.000666,-0.000026,0.000155,-0.000702,-0.004556,-0.004664,0.034122,-0.293375
V15,-0.184392,-0.000602,0.001538,-0.001230,0.000572,-0.001171,-0.000470,-0.001394,0.001044,-0.000283,...,-0.000271,-0.001197,0.000969,0.000113,0.000445,-0.002034,-0.000641,0.000858,-0.003265,-0.003300
V16,0.011286,-0.003345,0.004013,-0.004430,0.003346,-0.002373,0.000122,-0.005944,-0.004376,-0.000086,...,0.004326,-0.000820,0.001209,-0.000482,0.000215,-0.001245,-0.003974,-0.001629,-0.004488,-0.187186
V17,-0.073819,-0.003491,0.003244,-0.008159,0.003655,-0.004466,-0.001716,-0.008794,-0.005576,-0.002318,...,0.003560,-0.000162,0.000667,0.001006,-0.000685,0.000157,-0.003421,-0.002703,0.007730,-0.313498
V18,0.090305,-0.003535,0.002477,-0.003495,0.002325,-0.002685,0.000541,-0.004279,-0.001323,-0.000373,...,0.001629,-0.000533,0.000240,-0.000710,-0.000559,-0.000596,-0.004231,-0.001256,0.035775,-0.105340
V19,0.029537,0.000919,-0.000358,-0.000016,-0.000560,0.000436,0.000106,0.000846,-0.000626,0.000247,...,0.000244,0.001342,0.000381,-0.000112,-0.000084,0.000856,-0.000544,0.000353,-0.055994,0.033631
V20,-0.051022,-0.001393,-0.001287,-0.002269,0.000318,-0.001185,-0.000181,-0.001192,0.000271,-0.001838,...,0.005372,-0.001617,-0.001094,-0.000303,-0.000643,-0.000310,-0.000049,0.002671,0.340729,0.021486
V21,0.045913,0.002818,-0.004897,0.003500,-0.001034,0.001622,-0.002134,0.009010,0.018892,0.000679,...,1.000000,0.009645,-0.006391,0.001210,-0.000872,-0.000874,-0.005216,-0.004436,0.108058,0.026357
V22,0.143727,-0.001436,0.001237,-0.000275,0.000115,-0.000559,0.001104,-0.002280,-0.006156,0.000785,...,0.009645,1.000000,0.001929,-0.000031,0.000197,-0.001495,0.003037,0.001392,-0.064965,0.004887
V23,0.051474,-0.001330,-0.003855,0.000449,0.000732,0.001183,-0.000755,0.003303,0.004994,0.000677,...,-0.006391,0.001929,1.000000,0.000273,-0.000532,-0.000185,-0.002028,-0.003224,-0.112833,-0.006333
V24,-0.015954,-0.000723,0.000701,-0.000072,-0.000120,0.000198,0.001202,-0.000384,0.000113,-0.000103,...,0.001210,-0.000031,0.000273,1.000000,-0.000188,0.000568,-0.000885,0.000322,0.005055,-0.007210
V25,-0.233262,-0.000222,-0.001569,0.000425,0.000162,0.000069,0.000697,-0.000072,0.000011,-0.000275,...,-0.000872,0.000197,-0.000532,-0.000188,1.000000,0.000048,-0.001339,-0.000565,-0.047596,0.003202
V26,-0.041818,-0.000684,0.000253,-0.000094,0.000777,0.000390,-0.000028,0.000624,-0.001407,0.001253,...,-0.000874,-0.001495,-0.000185,0.000568,0.000048,1.000000,-0.003294,-0.000999,-0.003425,0.004265
V27,-0.005171,-0.015706,0.007555,-0.007051,0.001322,-0.005798,0.000289,-0.004537,0.000613,0.008221,...,-0.005216,0.003037,-0.002028,-0.000885,-0.001339,-0.003294,1.000000,-0.013950,0.027922,0.021892
V28,-0.009305,-0.004861,0.001611,-0.000134,0.000231,-0.000820,0.000925,0.001657,-0.000099,0.005591,...,-0.004436,0.001392,-0.003224,0.000322,-0.000565,-0.000999,-0.013950,1.000000,0.010143,0.009682
Amount,-0.010559,-0.230105,-0.533428,-0.212410,0.099514,-0.387685,0.216389,0.400408,-0.104662,-0.044123,...,0.108058,-0.064965,-0.112833,0.005055,-0.047596,-0.003425,0.027922,0.010143,1.000000,0.005777
Class,-0.012359,-0.094486,0.084624,-0.182322,0.129326,-0.087812,-0.043915,-0.172347,0.033068,-0.094021,...,0.026357,0.004887,-0.006333,-0.007210,0.003202,0.004265,0.021892,0.009682,0.005777,1.000000

In [12]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
X,y = smote.fit_resample(X,y)
y.value_counts()

Class
0    283253
1    283253
Name: count, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=42)

In [15]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((453204, 30), (113302, 30), (453204,), (113302,))

In [16]:
from sklearn.preprocessing import RobustScaler
rc = RobustScaler()
X_train[['Amount','Time']] = rc.fit_transform(X_train[['Amount','Time']])
X_test[['Amount','Time']] = rc.transform(X_test[['Amount','Time']])

In [17]:
X_train.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
303464,-0.787836,-1.788634,3.773586,-4.982108,3.538813,-1.578317,-2.465297,-3.877780,1.462213,-1.715969,...,0.527000,0.623596,-0.511996,-0.120711,0.005027,0.379780,0.351244,0.619855,0.353370,-0.252701
1934,-0.866694,-1.930422,1.778782,0.411402,-0.869500,-0.615354,-0.534365,-0.149129,0.955953,0.037004,...,0.014952,-0.105609,-0.447741,0.000562,0.006215,-0.100401,0.284431,-0.026413,0.162983,-0.252701
342085,-0.728700,-4.223158,7.728088,-14.315954,9.348611,-4.726379,-3.035494,-10.897963,4.781972,-5.087579,...,1.369595,1.993830,0.257683,0.618534,-1.090708,-0.769157,0.600754,1.558500,0.684775,-0.252701
224383,0.723659,-0.837795,0.482916,1.076006,-0.803303,0.885261,-0.465094,0.137538,0.215071,0.405346,...,0.274181,-0.319916,-0.944909,-0.125713,0.338428,0.536697,-0.142888,0.183155,0.049323,-0.183199
479262,-0.341563,-1.858129,1.657776,-0.950472,1.186714,-1.171675,-1.052750,-1.956126,0.662141,-1.288553,...,0.081987,0.654648,0.561973,-0.111295,0.112302,0.117378,-0.230051,-0.135557,-0.027463,-0.119406

In [18]:
data.corr()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
Time,1.000000,0.117927,-0.010556,-0.422054,-0.105845,0.173223,-0.063279,0.085335,-0.038203,-0.007861,...,0.045913,0.143727,0.051474,-0.015954,-0.233262,-0.041818,-0.005171,-0.009305,-0.010559,-0.012359
V1,0.117927,1.000000,0.006875,-0.008112,0.002257,-0.007036,0.000413,-0.009173,-0.001168,0.001828,...,0.002818,-0.001436,-0.001330,-0.000723,-0.000222,-0.000684,-0.015706,-0.004861,-0.230105,-0.094486
V2,-0.010556,0.006875,1.000000,0.005278,-0.001495,0.005210,-0.000594,0.007425,0.002899,-0.000274,...,-0.004897,0.001237,-0.003855,0.000701,-0.001569,0.000253,0.007555,0.001611,-0.533428,0.084624
V3,-0.422054,-0.008112,0.005278,1.000000,0.002829,-0.006879,-0.001511,-0.011721,-0.001815,-0.003579,...,0.003500,-0.000275,0.000449,-0.000072,0.000425,-0.000094,-0.007051,-0.000134,-0.212410,-0.182322
V4,-0.105845,0.002257,-0.001495,0.002829,1.000000,0.001744,-0.000880,0.004657,0.000890,0.002154,...,-0.001034,0.000115,0.000732,-0.000120,0.000162,0.000777,0.001322,0.000231,0.099514,0.129326
V5,0.173223,-0.007036,0.005210,-0.006879,0.001744,1.000000,-0.000938,-0.008709,0.001430,-0.001213,...,0.001622,-0.000559,0.001183,0.000198,0.000069,0.000390,-0.005798,-0.000820,-0.387685,-0.087812
V6,-0.063279,0.000413,-0.000594,-0.001511,-0.000880,-0.000938,1.000000,0.000436,0.003036,-0.000734,...,-0.002134,0.001104,-0.000755,0.001202,0.000697,-0.000028,0.000289,0.000925,0.216389,-0.043915
V7,0.085335,-0.009173,0.007425,-0.011721,0.004657,-0.008709,0.000436,1.000000,-0.006419,-0.004921,...,0.009010,-0.002280,0.003303,-0.000384,-0.000072,0.000624,-0.004537,0.001657,0.400408,-0.172347
V8,-0.038203,-0.001168,0.002899,-0.001815,0.000890,0.001430,0.003036,-0.006419,1.000000,0.001038,...,0.018892,-0.006156,0.004994,0.000113,0.000011,-0.001407,0.000613,-0.000099,-0.104662,0.033068
V9,-0.007861,0.001828,-0.000274,-0.003579,0.002154,-0.001213,-0.000734,-0.004921,0.001038,1.000000,...,0.000679,0.000785,0.000677,-0.000103,-0.000275,0.001253,0.008221,0.005591,-0.044123,-0.094021
V10,0.031068,0.000815,0.000620,-0.009632,0.002753,-0.006050,-0.002180,-0.013617,0.000481,-0.012613,...,0.003777,-0.000481,0.001917,0.000154,-0.000565,0.001089,0.010769,0.009159,-0.102255,-0.206971
V11,-0.248536,0.001028,-0.000633,0.002339,-0.001223,0.000411,-0.000211,0.002454,0.004688,-0.000217,...,-0.002760,-0.000150,-0.000037,0.000080,0.000047,-0.000204,0.001987,0.002562,-0.000015,0.149067
V12,0.125500,-0.001524,0.002266,-0.005900,0.003366,-0.002342,-0.001185,-0.006153,-0.004414,-0.002385,...,0.003285,0.000151,0.000486,0.000588,-0.000181,-0.000138,-0.000929,-0.000613,-0.009254,-0.250711
V13,-0.065958,-0.000568,0.000680,0.000113,0.000177,0.000019,0.000397,-0.000170,-0.001381,0.000745,...,0.000522,0.000016,0.000252,-0.000049,0.000248,-0.000101,-0.001577,-0.000604,0.005209,-0.003897
V14,-0.100316,-0.002663,0.002711,-0.003027,0.002801,-0.001000,0.000184,-0.003816,-0.008387,0.001981,...,0.005633,-0.001906,0.000666,-0.000026,0.000155,-0.000702,-0.004556,-0.004664,0.034122,-0.293375
V15,-0.184392,-0.000602,0.001538,-0.001230,0.000572,-0.001171,-0.000470,-0.001394,0.001044,-0.000283,...,-0.000271,-0.001197,0.000969,0.000113,0.000445,-0.002034,-0.000641,0.000858,-0.003265,-0.003300
V16,0.011286,-0.003345,0.004013,-0.004430,0.003346,-0.002373,0.000122,-0.005944,-0.004376,-0.000086,...,0.004326,-0.000820,0.001209,-0.000482,0.000215,-0.001245,-0.003974,-0.001629,-0.004488,-0.187186
V17,-0.073819,-0.003491,0.003244,-0.008159,0.003655,-0.004466,-0.001716,-0.008794,-0.005576,-0.002318,...,0.003560,-0.000162,0.000667,0.001006,-0.000685,0.000157,-0.003421,-0.002703,0.007730,-0.313498
V18,0.090305,-0.003535,0.002477,-0.003495,0.002325,-0.002685,0.000541,-0.004279,-0.001323,-0.000373,...,0.001629,-0.000533,0.000240,-0.000710,-0.000559,-0.000596,-0.004231,-0.001256,0.035775,-0.105340
V19,0.029537,0.000919,-0.000358,-0.000016,-0.000560,0.000436,0.000106,0.000846,-0.000626,0.000247,...,0.000244,0.001342,0.000381,-0.000112,-0.000084,0.000856,-0.000544,0.000353,-0.055994,0.033631
V20,-0.051022,-0.001393,-0.001287,-0.002269,0.000318,-0.001185,-0.000181,-0.001192,0.000271,-0.001838,...,0.005372,-0.001617,-0.001094,-0.000303,-0.000643,-0.000310,-0.000049,0.002671,0.340729,0.021486
V21,0.045913,0.002818,-0.004897,0.003500,-0.001034,0.001622,-0.002134,0.009010,0.018892,0.000679,...,1.000000,0.009645,-0.006391,0.001210,-0.000872,-0.000874,-0.005216,-0.004436,0.108058,0.026357
V22,0.143727,-0.001436,0.001237,-0.000275,0.000115,-0.000559,0.001104,-0.002280,-0.006156,0.000785,...,0.009645,1.000000,0.001929,-0.000031,0.000197,-0.001495,0.003037,0.001392,-0.064965,0.004887
V23,0.051474,-0.001330,-0.003855,0.000449,0.000732,0.001183,-0.000755,0.003303,0.004994,0.000677,...,-0.006391,0.001929,1.000000,0.000273,-0.000532,-0.000185,-0.002028,-0.003224,-0.112833,-0.006333
V24,-0.015954,-0.000723,0.000701,-0.000072,-0.000120,0.000198,0.001202,-0.000384,0.000113,-0.000103,...,0.001210,-0.000031,0.000273,1.000000,-0.000188,0.000568,-0.000885,0.000322,0.005055,-0.007210
V25,-0.233262,-0.000222,-0.001569,0.000425,0.000162,0.000069,0.000697,-0.000072,0.000011,-0.000275,...,-0.000872,0.000197,-0.000532,-0.000188,1.000000,0.000048,-0.001339,-0.000565,-0.047596,0.003202
V26,-0.041818,-0.000684,0.000253,-0.000094,0.000777,0.000390,-0.000028,0.000624,-0.001407,0.001253,...,-0.000874,-0.001495,-0.000185,0.000568,0.000048,1.000000,-0.003294,-0.000999,-0.003425,0.004265
V27,-0.005171,-0.015706,0.007555,-0.007051,0.001322,-0.005798,0.000289,-0.004537,0.000613,0.008221,...,-0.005216,0.003037,-0.002028,-0.000885,-0.001339,-0.003294,1.000000,-0.013950,0.027922,0.021892
V28,-0.009305,-0.004861,0.001611,-0.000134,0.000231,-0.000820,0.000925,0.001657,-0.000099,0.005591,...,-0.004436,0.001392,-0.003224,0.000322,-0.000565,-0.000999,-0.013950,1.000000,0.010143,0.009682
Amount,-0.010559,-0.230105,-0.533428,-0.212410,0.099514,-0.387685,0.216389,0.400408,-0.104662,-0.044123,...,0.108058,-0.064965,-0.112833,0.005055,-0.047596,-0.003425,0.027922,0.010143,1.000000,0.005777
Class,-0.012359,-0.094486,0.084624,-0.182322,0.129326,-0.087812,-0.043915,-0.172347,0.033068,-0.094021,...,0.026357,0.004887,-0.006333,-0.007210,0.003202,0.004265,0.021892,0.009682,0.005777,1.000000

In [19]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

In [20]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,609 (18.00 KB)

 Trainable params: 4,609 (18.00 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.compile(optimizer='adam',loss='mse',metrics=['r2_score'])

In [23]:
model.fit(X_train,y_train,epochs=20,batch_size=64)

Epoch 1/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 0.0048 - r2_score: 0.9808
Epoch 2/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 0.0014 - r2_score: 0.9946
Epoch 3/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 9.8296e-04 - r2_score: 0.9961
Epoch 4/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 7.6430e-04 - r2_score: 0.9969
Epoch 5/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 6.7104e-04 - r2_score: 0.9973
Epoch 6/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 6.6704e-04 - r2_score: 0.9973
Epoch 7/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 5.9123e-04 - r2_score: 0.9976
Epoch 8/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 5.6817e-04 - r2_score: 0.9977
Epoch 9/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 4.8831e-04 - r2_score: 0.9980
Epoch 10/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 4.9521e-04 - r2_score: 0.9980
Epoch 11/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 4.4472e-04 - r2_score: 0.9982
Epoch 12/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 4.4886e-04 - r2_score: 0.9982
Epoch 13/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 4.1714e-04 - r2_score: 0.9983
Epoch 14/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 4.1729e-04 - r2_score: 0.9983
Epoch 15/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 3.8894e-04 - r2_score: 0.9984
Epoch 16/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 4.0726e-04 - r2_score: 0.9984
Epoch 17/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 3.3660e-04 - r2_score: 0.9987
Epoch 18/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 3.6859e-04 - r2_score: 0.9985
Epoch 19/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 3.1163e-04 - r2_score: 0.9988
Epoch 20/20
7082/7082 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 3.7203e-04 - r2_score: 0.9985

In [24]:
model.evaluate(X_test,y_test)

3541/3541 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 2.8672e-04 - r2_score: 0.9989

[0.0002867175790015608, 0.9988530874252319]

In [56]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, f1_score, recall_score

In [27]:
y_pred_prob = model.predict(X_test)

3541/3541 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step

In [28]:
y_pred = (y_pred_prob>0.5).astype(int)

In [29]:
confusion_matrix(y_test, y_pred)

array([[56429,    34],
       [    2, 56837]])

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56463
           1       1.00      1.00      1.00     56839

    accuracy                           1.00    113302
   macro avg       1.00      1.00      1.00    113302
weighted avg       1.00      1.00      1.00    113302

In [31]:
model_2 = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(64, activation='tanh'),
    layers.Dense(32, activation='tanh'),
    layers.Dense(16, activation='tanh'),
    layers.Dense(1, activation='sigmoid')
])

In [36]:
model_2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,609 (18.00 KB)

 Trainable params: 4,609 (18.00 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model_2.compile(optimizer='sgd',loss='mse',metrics=['r2_score'])

In [38]:
model_2.fit(X_train,y_train,epochs=50,batch_size=128)

Epoch 1/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 0.0358 - r2_score: 0.8567
Epoch 2/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0174 - r2_score: 0.9303
Epoch 3/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0148 - r2_score: 0.9410
Epoch 4/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0132 - r2_score: 0.9473
Epoch 5/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0121 - r2_score: 0.9517
Epoch 6/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0112 - r2_score: 0.9550
Epoch 7/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 0.0106 - r2_score: 0.9577
Epoch 8/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0100 - r2_score: 0.9599
Epoch 9/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 0.0095 - r2_score: 0.9619
Epoch 10/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0091 - r2_score: 0.9637
Epoch 11/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0086 - r2_score: 0.9655
Epoch 12/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0081 - r2_score: 0.9674
Epoch 13/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0077 - r2_score: 0.9693
Epoch 14/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0072 - r2_score: 0.9711
Epoch 15/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0068 - r2_score: 0.9727
Epoch 16/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0064 - r2_score: 0.9742
Epoch 17/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0061 - r2_score: 0.9756
Epoch 18/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0058 - r2_score: 0.9769
Epoch 19/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0055 - r2_score: 0.9780
Epoch 20/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0052 - r2_score: 0.9791
Epoch 21/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0050 - r2_score: 0.9801
Epoch 22/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0047 - r2_score: 0.9811
Epoch 23/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 0.0045 - r2_score: 0.9820
Epoch 24/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0043 - r2_score: 0.9828
Epoch 25/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0041 - r2_score: 0.9837
Epoch 26/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0039 - r2_score: 0.9845
Epoch 27/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0037 - r2_score: 0.9853
Epoch 28/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0035 - r2_score: 0.9861
Epoch 29/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0033 - r2_score: 0.9868
Epoch 30/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0031 - r2_score: 0.9874
Epoch 31/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0030 - r2_score: 0.9880
Epoch 32/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0029 - r2_score: 0.9885
Epoch 33/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0027 - r2_score: 0.9890
Epoch 34/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 0.0026 - r2_score: 0.9895
Epoch 35/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0025 - r2_score: 0.9899
Epoch 36/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 0.0024 - r2_score: 0.9903
Epoch 37/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0023 - r2_score: 0.9906
Epoch 38/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0023 - r2_score: 0.9909
Epoch 39/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0022 - r2_score: 0.9912
Epoch 40/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0021 - r2_score: 0.9915
Epoch 41/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0020 - r2_score: 0.9918
Epoch 42/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0020 - r2_score: 0.9921
Epoch 43/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0019 - r2_score: 0.9923
Epoch 44/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0019 - r2_score: 0.9925
Epoch 45/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0018 - r2_score: 0.9927
Epoch 46/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0018 - r2_score: 0.9929
Epoch 47/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0017 - r2_score: 0.9931
Epoch 48/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 0.0017 - r2_score: 0.9933
Epoch 49/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0016 - r2_score: 0.9935
Epoch 50/50
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0016 - r2_score: 0.9937

In [39]:
model.evaluate(X_test,y_test)

3541/3541 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 2.8672e-04 - r2_score: 0.9989

[0.0002867175790015608, 0.9988530874252319]

In [40]:
y_pred_prob = model_2.predict(X_test)

3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step

In [41]:
y_pred = (y_pred_prob>0.5).astype(int)

In [42]:
confusion_matrix(y_test, y_pred)

array([[56339,   124],
       [   68, 56771]])

In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56463
           1       1.00      1.00      1.00     56839

    accuracy                           1.00    113302
   macro avg       1.00      1.00      1.00    113302
weighted avg       1.00      1.00      1.00    113302

In [44]:
model_3 = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(64, activation='tanh'),
    layers.Dense(32, activation='tanh'),
    layers.Dense(16, activation='tanh'),
    layers.Dense(1, activation='sigmoid')
])

In [45]:
model_3.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 64)             │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,609 (18.00 KB)

 Trainable params: 4,609 (18.00 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
model_3.compile(optimizer='rmsprop',loss='mse',metrics=['r2_score'])

In [48]:
model_3.fit(X_train,y_train,epochs=100,batch_size=256)

Epoch 1/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 0.0090 - r2_score: 0.9641
Epoch 2/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 0.0025 - r2_score: 0.9899
Epoch 3/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 0.0016 - r2_score: 0.9937
Epoch 4/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 0.0012 - r2_score: 0.9954
Epoch 5/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 9.2041e-04 - r2_score: 0.9963
Epoch 6/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 7.6733e-04 - r2_score: 0.9969
Epoch 7/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6.8521e-04 - r2_score: 0.9973
Epoch 8/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 5.9050e-04 - r2_score: 0.9976
Epoch 9/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5.4192e-04 - r2_score: 0.9978
Epoch 10/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 4.9197e-04 - r2_score: 0.9980
Epoch 11/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 4.6089e-04 - r2_score: 0.9982
Epoch 12/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4.1418e-04 - r2_score: 0.9983
Epoch 13/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 3.9355e-04 - r2_score: 0.9984
Epoch 14/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 3.7374e-04 - r2_score: 0.9985
Epoch 15/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 3.3689e-04 - r2_score: 0.9987
Epoch 16/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 3.0802e-04 - r2_score: 0.9988
Epoch 17/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 2.9996e-04 - r2_score: 0.9988
Epoch 18/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 3.1369e-04 - r2_score: 0.9987
Epoch 19/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2.9792e-04 - r2_score: 0.9988
Epoch 20/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 2.8437e-04 - r2_score: 0.9989
Epoch 21/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 2.7937e-04 - r2_score: 0.9989
Epoch 22/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2.4734e-04 - r2_score: 0.9990
Epoch 23/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2.4735e-04 - r2_score: 0.9990
Epoch 24/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2.3866e-04 - r2_score: 0.9990
Epoch 25/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2.3276e-04 - r2_score: 0.9991
Epoch 26/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 2.2096e-04 - r2_score: 0.9991
Epoch 27/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 2.3412e-04 - r2_score: 0.9991
Epoch 28/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 2.2315e-04 - r2_score: 0.9991
Epoch 29/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 2.1241e-04 - r2_score: 0.9992
Epoch 30/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2.0762e-04 - r2_score: 0.9992
Epoch 31/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 2.2389e-04 - r2_score: 0.9991
Epoch 32/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2.0922e-04 - r2_score: 0.9992
Epoch 33/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2.0339e-04 - r2_score: 0.9992
Epoch 34/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 2.1161e-04 - r2_score: 0.9992
Epoch 35/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2.0709e-04 - r2_score: 0.9992
Epoch 36/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 2.0528e-04 - r2_score: 0.9992
Epoch 37/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 2.0581e-04 - r2_score: 0.9992
Epoch 38/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 2.0568e-04 - r2_score: 0.9992
Epoch 39/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 2.0456e-04 - r2_score: 0.9992
Epoch 40/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.9072e-04 - r2_score: 0.9992
Epoch 41/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.8912e-04 - r2_score: 0.9992
Epoch 42/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.8171e-04 - r2_score: 0.9993
Epoch 43/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.8107e-04 - r2_score: 0.9993
Epoch 44/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 1.7928e-04 - r2_score: 0.9993
Epoch 45/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 1.8159e-04 - r2_score: 0.9993
Epoch 46/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 1.8005e-04 - r2_score: 0.9993
Epoch 47/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 1.8565e-04 - r2_score: 0.9993
Epoch 48/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 1.8181e-04 - r2_score: 0.9993
Epoch 49/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.7781e-04 - r2_score: 0.9993
Epoch 50/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.8438e-04 - r2_score: 0.9993
Epoch 51/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.7776e-04 - r2_score: 0.9993
Epoch 52/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.8302e-04 - r2_score: 0.9993
Epoch 53/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.8250e-04 - r2_score: 0.9993
Epoch 54/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8177e-04 - r2_score: 0.9993
Epoch 55/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 1.7373e-04 - r2_score: 0.9993
Epoch 56/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.7418e-04 - r2_score: 0.9993
Epoch 57/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.7600e-04 - r2_score: 0.9993
Epoch 58/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.7434e-04 - r2_score: 0.9993
Epoch 59/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.7502e-04 - r2_score: 0.9993
Epoch 60/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.7538e-04 - r2_score: 0.9993
Epoch 61/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.7010e-04 - r2_score: 0.9993
Epoch 62/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.8873e-04 - r2_score: 0.9992
Epoch 63/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.7142e-04 - r2_score: 0.9993
Epoch 64/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.7336e-04 - r2_score: 0.9993
Epoch 65/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.6827e-04 - r2_score: 0.9993
Epoch 66/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.6709e-04 - r2_score: 0.9993
Epoch 67/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.5704e-04 - r2_score: 0.9994
Epoch 68/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.6943e-04 - r2_score: 0.9993
Epoch 69/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.6855e-04 - r2_score: 0.9993
Epoch 70/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.6213e-04 - r2_score: 0.9994
Epoch 71/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.6939e-04 - r2_score: 0.9993
Epoch 72/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.5778e-04 - r2_score: 0.9994
Epoch 73/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.5328e-04 - r2_score: 0.9994
Epoch 74/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 1.5597e-04 - r2_score: 0.9994
Epoch 75/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.5479e-04 - r2_score: 0.9994
Epoch 76/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.5686e-04 - r2_score: 0.9994
Epoch 77/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.5712e-04 - r2_score: 0.9994
Epoch 78/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.5565e-04 - r2_score: 0.9994
Epoch 79/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.4528e-04 - r2_score: 0.9994
Epoch 80/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.5074e-04 - r2_score: 0.9994
Epoch 81/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.4366e-04 - r2_score: 0.9994
Epoch 82/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.4959e-04 - r2_score: 0.9994
Epoch 83/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.6013e-04 - r2_score: 0.9994
Epoch 84/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.5702e-04 - r2_score: 0.9994
Epoch 85/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.4694e-04 - r2_score: 0.9994
Epoch 86/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.4736e-04 - r2_score: 0.9994
Epoch 87/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.4735e-04 - r2_score: 0.9994
Epoch 88/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.4669e-04 - r2_score: 0.9994
Epoch 89/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.4979e-04 - r2_score: 0.9994
Epoch 90/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.4789e-04 - r2_score: 0.9994
Epoch 91/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.4869e-04 - r2_score: 0.9994
Epoch 92/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.4981e-04 - r2_score: 0.9994
Epoch 93/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.4238e-04 - r2_score: 0.9994
Epoch 94/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.4878e-04 - r2_score: 0.9994
Epoch 95/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.4484e-04 - r2_score: 0.9994
Epoch 96/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.5010e-04 - r2_score: 0.9994
Epoch 97/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.4980e-04 - r2_score: 0.9994
Epoch 98/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 1.4127e-04 - r2_score: 0.9994
Epoch 99/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.3858e-04 - r2_score: 0.9994
Epoch 100/100
1771/1771 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1.4111e-04 - r2_score: 0.9994

In [50]:
y_pred1 = (model.predict(X_test) > 0.5).astype(int)
y_pred2 = (model_2.predict(X_test) > 0.5).astype(int)
y_pred3 = (model_3.predict(X_test) > 0.5).astype(int)

3541/3541 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step
3541/3541 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step

In [57]:
comparison_data = {
    'Model': ['Model 1', 'Model 2', 'Model 3'],
    'Activation':['ReLU', 'Tanh', 'Sigmoid'],
    'Optimizer': ['Adam', 'SGD', 'RMSprop'],
    'Epochs':[20,50,100],
    'Accuracy':[
        round(accuracy_score(y_test, y_pred1), 4),
        round(accuracy_score(y_test, y_pred2), 4),
        round(accuracy_score(y_test, y_pred3), 4)
    ],
    'Precision': [
        round(precision_score(y_test, y_pred1, zero_division=0), 4),
        round(precision_score(y_test, y_pred2, zero_division=0), 4),
        round(precision_score(y_test, y_pred3, zero_division=0), 4)
    ],
    'Recall': [
        round(recall_score(y_test, y_pred1, zero_division=0), 4),
        round(recall_score(y_test, y_pred2, zero_division=0), 4),
        round(recall_score(y_test, y_pred3, zero_division=0), 4)
    ],
    'F1-Score': [
        round(f1_score(y_test, y_pred1, zero_division=0), 4),
        round(f1_score(y_test, y_pred2, zero_division=0), 4),
        round(f1_score(y_test, y_pred3, zero_division=0), 4)
    ]}

In [58]:
df_comparison = pd.DataFrame(comparison_data)

In [59]:
display(df_comparison)

     Model Activation Optimizer  Epochs  Accuracy  Precision  Recall  F1-Score
0  Model 1       ReLU      Adam      20    0.9997     0.9994  1.0000    0.9997
1  Model 2       Tanh       SGD      50    0.9983     0.9978  0.9988    0.9983
2  Model 3    Sigmoid   RMSprop     100    0.9997     0.9993  1.0000    0.9997